# Generated by Django 3.2.16 on 2022-10-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
        ),
    ]
