# Generated by Django 4.1 on 2022-10-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='relatedcnpj',
            old_name='company',
            new_name='client',
        ),
    ]
