# Generated by Django 4.1.2 on 2022-10-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_relatedcnpjhistory_clienthistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienthistory',
            table='client_history',
        ),
        migrations.AlterModelTable(
            name='relatedcnpjhistory',
            table='relatedcnpj_history',
        ),
    ]
