# Generated by Django 4.1.2 on 2022-10-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clienthistory_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienthistory',
            table='client_client_history',
        ),
        migrations.AlterModelTable(
            name='relatedcnpjhistory',
            table='client_relatedcnpj_history',
        ),
    ]
