# Generated by Django 4.1.2 on 2022-10-24 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_client_id_clienthistory_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='relatedcnpj',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='relatedcnpj',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='relatedcnpjhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em'),
        ),
    ]
